name: Add jar to release

on:
  release:
    types: [published]

jobs:
  build:
    name: Add jar to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate jar
        run: ./gradlew jar
      - name: Upload jar
        uses: AButler/upload-release-assets@v3.0
        with:
          files: build/libs/*.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}